[@tree:view id="myTree"]
	[%node id="n1" label="Label 1" href="http://www.google.com"]
		[%node id="n1_1" label="Label 1.1"/]
		[%node id="n1_2" label="Label 1.2" tooltip="This is a tooltip"/]
		[%node id="n1_3" label="Label 1.3" tooltip="This is another tooltip"]
			[%node id="n1_3_1" label="Label 1.3.1"/]
		[/%node]
	[/%node]
	[%node id="n2" label="Label 2"]
		[%node id="n2_1" label="Label 2.1" href="http://www.google.com"/]
	[/%node]
	[%node id="n3" label="Label 3" href="http://www.google.com"/]
[/@tree:view]
